/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dtos.AnalisisDTO;
import dtos.MuestraDTO;
import dtos.ParametroDTO;
import Exception.NegocioException;
import servicios.AnalisisService;
import servicios.MuestraService;

/**
 *
 * @author rafaelgb
 */
public class frmNuevo_Analisis extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmNuevo_Analisis.class.getName());
    private pantallas.frmPrincipal_Catalago padre;
    private AnalisisService analisisService;
    private MuestraService muestraService;
    private List<MuestraDTO> muestrasCargadas = new ArrayList<>();
    private List<ParametroDTO> parametrosTemp = new ArrayList<>();
    private DefaultTableModel modeloParametros;
    /**
     * Creates new form frmNuevo_Analisis
     */
    public frmNuevo_Analisis() {
        initComponents();
        
        tblParametros.getTableHeader().setPreferredSize(
                new Dimension(tblParametros.getTableHeader().getPreferredSize().width, 30));
        
        this.analisisService = new AnalisisService();
        this.muestraService = new MuestraService();

        this.modeloParametros = new DefaultTableModel(new Object[]{"Nombre", "Unidad", "Rangos de Referencia"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblParametros.setModel(modeloParametros);

        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        cargarMuestras();
    }
    
    public frmNuevo_Analisis(pantallas.frmPrincipal_Catalago padre) {
        this();
        this.padre = padre;
    }
    
    private void cargarMuestras() {
        try {
            muestrasCargadas = muestraService.obtenerTodas();
            cmbMuestras.removeAllItems();
            for (MuestraDTO m : muestrasCargadas) {
                cmbMuestras.addItem(m.getNombre());
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public String getNombreAnalisisIngresado() {
        return txtNmbAnalisis.getText();
    }

    public void agregarParametro(ParametroDTO parametro) {
        parametrosTemp.add(parametro);
        modeloParametros.addRow(new Object[]{parametro.getNombre(), parametro.getNombreUnidadMedida(), parametro.getRangosResumen()});
    }
    
    public int getSiguienteOrdenParametro() {
        return parametrosTemp.size() + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        cmbMuestras = new javax.swing.JComboBox<>();
        lblNmbAnalisis = new javax.swing.JLabel();
        lblTipoMuestra = new javax.swing.JLabel();
        txtNmbAnalisis = new javax.swing.JTextField();
        lblParametros = new javax.swing.JLabel();
        btnAgrParametro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParametros = new javax.swing.JTable();
        lblNota = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(231, 239, 246));

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitulo.setText("Nuevo Análisis");

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        cmbMuestras.setBackground(new java.awt.Color(230, 238, 244));
        cmbMuestras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMuestras.addActionListener(this::cmbMuestrasActionPerformed);

        lblNmbAnalisis.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblNmbAnalisis.setText("Nombre del análisis");

        lblTipoMuestra.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTipoMuestra.setText("Tipo de muestra");

        txtNmbAnalisis.setBackground(new java.awt.Color(230, 238, 244));
        txtNmbAnalisis.setText("Ej. Glucosa de sangre");
        txtNmbAnalisis.addActionListener(this::txtNmbAnalisisActionPerformed);

        lblParametros.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblParametros.setText("Parámetros configurados");

        btnAgrParametro.setBackground(new java.awt.Color(0, 51, 102));
        btnAgrParametro.setForeground(new java.awt.Color(255, 255, 255));
        btnAgrParametro.setText("Agregar Parámetro");
        btnAgrParametro.addActionListener(this::btnAgrParametroActionPerformed);

        tblParametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Unidad", "<html><center>Rangos de<br>Referencia</center></html>", "Eliminar"
            }
        ));
        jScrollPane1.setViewportView(tblParametros);

        lblNota.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblNota.setText("Nota Descriptiva");

        txtNota.setBackground(new java.awt.Color(230, 238, 244));
        txtNota.setText("Instrucciones especificas, estabilidad de la muestra o observaciones clinicas... ");
        txtNota.addActionListener(this::txtNotaActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 51, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(0, 51, 102));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Análisis");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addComponent(lblNota)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                        .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContenidoLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addGroup(pnlContenidoLayout.createSequentialGroup()
                                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNmbAnalisis)
                                    .addComponent(lblParametros)
                                    .addComponent(txtNmbAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgrParametro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                                        .addComponent(lblTipoMuestra)
                                        .addGap(98, 98, 98))
                                    .addComponent(cmbMuestras, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(38, 38, 38))))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMuestra)
                    .addComponent(lblNmbAnalisis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNmbAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgrParametro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblParametros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNmbAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmbAnalisisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmbAnalisisActionPerformed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (padre != null) {
            padre.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbMuestrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMuestrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMuestrasActionPerformed

    private void btnAgrParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrParametroActionPerformed
        // TODO add your handling code here:
        if (txtNmbAnalisis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero escribe el nombre del análisis.", "Falta información", JOptionPane.WARNING_MESSAGE);
            return;
        }
        frmParametro frm = new frmParametro(this);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgrParametroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNmbAnalisis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del análisis es obligatorio.", "Falta información", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cmbMuestras.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona el tipo de muestra.", "Falta información", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (parametrosTemp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos un parámetro.", "Falta información", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            AnalisisDTO dto = new AnalisisDTO();
            dto.setNombre(txtNmbAnalisis.getText().trim());
            dto.setNotaDescriptiva(txtNota.getText().trim());
            dto.setMuestraId(muestrasCargadas.get(cmbMuestras.getSelectedIndex()).getId());
            dto.setParametros(parametrosTemp);

            analisisService.guardarAnalisisCompleto(dto);

            JOptionPane.showMessageDialog(this, "Análisis guardado correctamente.");
            if (padre != null) {
                padre.setVisible(true);
            }
            this.dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al guardar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmNuevo_Analisis().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrParametro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbMuestras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNmbAnalisis;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblParametros;
    private javax.swing.JLabel lblTipoMuestra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblParametros;
    private javax.swing.JTextField txtNmbAnalisis;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
