/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import Exception.NegocioException;
import daos.AnalisisDAO;
import dtos.AnalisisDTO;
import dtos.ClienteDTO;
import dtos.DoctorDTO;
import dtos.ParametroDTO;
import dtos.PruebaDetalleDTO;
import dtos.PruebaResumenDTO;
import entidades.AnalisisEntidad;
import entidades.ParametroEntidad;
import exception.PersistenciaException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.ClienteService;
import servicios.DoctorService;
import servicios.ParametroService;
import servicios.PruebaService;
import servicios.ResultadoService;
import entidades.PruebaEntidad;

/**
 *
 * @author golea
 */
public class Ingreso_resultados extends javax.swing.JFrame {

    private DoctorService doctorService = new DoctorService();
    private ClienteService clienteService = new ClienteService();
    private PruebaService pruebaService = new PruebaService();
    private daos.PruebaDAO pruebaDAO = new daos.PruebaDAO(new conexion.ConexionBD());
    private List<ParametroDTO> listaParametrosCargados;

    private AnalisisDAO analisisDAO = new AnalisisDAO(new conexion.ConexionBD());
    private ParametroService parametroService = new ParametroService();
    private List<DoctorDTO> listaDoctores;

    private List<AnalisisDTO> listaAnalisisActuales = new ArrayList<>();

    private ResultadoService resultadoService = new ResultadoService();
    private Long idPruebaActual;

   
    public Ingreso_resultados() throws PersistenciaException {
        initComponents();
        cargarDoctores();
        jtableparametros.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer());
    }

    private void cargarDoctores() {

        try {
            // Esta es la línea que está dando el error de compilación
            this.listaDoctores = doctorService.obtenerDoctores();

            cbxmedicos.removeAllItems();
            for (DoctorDTO doc : listaDoctores) {
                cbxmedicos.addItem(doc.getNombreCompleto());
            }
        } catch (NegocioException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al cargar la lista de médicos: " + e.getMessage(),
                    "Error de sistema",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarAnalisisEnCombo(Long idPrueba) {
        try {
            // 1. Limpiamos ambos
            listaAnalisisActuales.clear();
            cbxanalisis.removeAllItems();

            // 2. Obtenemos los datos del DAO
            List<AnalisisEntidad> entidades = analisisDAO.consultarAnalisisPorPrueba(idPrueba);

            // 3. Llenamos y sincronizamos
            for (AnalisisEntidad e : entidades) {
                AnalisisDTO dto = new AnalisisDTO(e.getId_analisis(), e.getNombre());
                listaAnalisisActuales.add(dto);
                cbxanalisis.addItem(dto.getNombre());
            }

            System.out.println("Análisis cargados: " + listaAnalisisActuales.size());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar análisis: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPMENUDEPRINCIPAL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btncatalogo = new javax.swing.JButton();
        btnsolicitudes = new javax.swing.JButton();
        btnresultados = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxmedicos = new javax.swing.JComboBox<>();
        btncambiarmedico = new javax.swing.JButton();
        JPPENDIENTES = new javax.swing.JPanel();
        lblpendientes = new javax.swing.JLabel();
        jlistadependientes = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btncapturar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblnombredelpaciente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblescribirid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblescribirsexo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblnombremedico = new javax.swing.JLabel();
        lblescribirfechadetoma = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableparametros = new javax.swing.JTable();
        cbxanalisis = new javax.swing.JComboBox<>();
        btncambiar = new javax.swing.JButton();
        lblEscribirfolio = new javax.swing.JLabel();
        btnguardarparametros = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobservacion = new javax.swing.JTextArea();
        lblobservacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPMENUDEPRINCIPAL.setBackground(new java.awt.Color(31, 41, 55));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salud Total");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion de Laboratorio");

        btncatalogo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btncatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btncatalogo.setText("Catalogo");
        btncatalogo.setBorder(null);
        btncatalogo.setContentAreaFilled(false);
        btncatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalogoActionPerformed(evt);
            }
        });

        btnsolicitudes.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnsolicitudes.setForeground(new java.awt.Color(255, 255, 255));
        btnsolicitudes.setText("Solicitudes");
        btnsolicitudes.setContentAreaFilled(false);
        btnsolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolicitudesActionPerformed(evt);
            }
        });

        btnresultados.setBackground(new java.awt.Color(0, 153, 255));
        btnresultados.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnresultados.setForeground(new java.awt.Color(255, 255, 255));
        btnresultados.setText("Resultados");
        btnresultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresultadosActionPerformed(evt);
            }
        });

        btnreportes.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(255, 255, 255));
        btnreportes.setText("Reportes");
        btnreportes.setToolTipText("");
        btnreportes.setContentAreaFilled(false);
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPMENUDEPRINCIPALLayout = new javax.swing.GroupLayout(JPMENUDEPRINCIPAL);
        JPMENUDEPRINCIPAL.setLayout(JPMENUDEPRINCIPALLayout);
        JPMENUDEPRINCIPALLayout.setHorizontalGroup(
            JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMENUDEPRINCIPALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnreportes, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncatalogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsolicitudes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(btnresultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPMENUDEPRINCIPALLayout.setVerticalGroup(
            JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMENUDEPRINCIPALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(114, 114, 114)
                .addComponent(btncatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnresultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreportes)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jPanel1.add(JPMENUDEPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 690));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Ingreso de Resultados");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Medico en turno");

        cbxmedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncambiarmedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncambiarmedico.setForeground(new java.awt.Color(0, 153, 255));
        btncambiarmedico.setText("cambiar");
        btncambiarmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiarmedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbxmedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncambiarmedico)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxmedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncambiarmedico)
                            .addComponent(jLabel4))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 970, 50));

        lblpendientes.setText("PENDIENTES");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistadependientes.setViewportView(jList1);

        btncapturar.setText("capturar");
        btncapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapturarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPPENDIENTESLayout = new javax.swing.GroupLayout(JPPENDIENTES);
        JPPENDIENTES.setLayout(JPPENDIENTESLayout);
        JPPENDIENTESLayout.setHorizontalGroup(
            JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPENDIENTESLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlistadependientes)
                    .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                        .addComponent(lblpendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btncapturar)))
                .addGap(36, 36, 36))
        );
        JPPENDIENTESLayout.setVerticalGroup(
            JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpendientes)
                    .addComponent(btncapturar))
                .addGap(34, 34, 34)
                .addComponent(jlistadependientes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jPanel1.add(JPPENDIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 260, 640));

        lblnombredelpaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombredelpaciente.setText("NOMBRE DEL PACIENTE SELECIONADO");

        jLabel9.setText("ID:");

        lblescribirid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblescribirid.setText("escribir id");

        jLabel11.setText("Sexo:");

        lblescribirsexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblescribirsexo.setText("escribir sexo");

        jLabel13.setText("fecha de toma:");

        lblnombremedico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblnombremedico.setText("nombre del medico");

        lblescribirfechadetoma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblescribirfechadetoma.setText("escribir la fecha de toma");

        jLabel16.setText("Medico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblescribirid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(lblescribirsexo)))
                        .addGap(56, 56, 56)
                        .addComponent(lblnombremedico, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblnombredelpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblescribirfechadetoma, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnombredelpaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblescribirid)
                    .addComponent(lblescribirsexo)
                    .addComponent(lblnombremedico)
                    .addComponent(lblescribirfechadetoma))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel16)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 660, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("CAPTURA DE PARAMETROS");

        jtableparametros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtableparametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Parametro", "valor", "rango normal", "unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableparametros);

        cbxanalisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btncambiar.setText("cambiar");
        btncambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiarActionPerformed(evt);
            }
        });

        lblEscribirfolio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEscribirfolio.setText("escribir folio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEscribirfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btncambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEscribirfolio))
                    .addComponent(btncambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 660, 350));

        btnguardarparametros.setText("guardar");
        btnguardarparametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarparametrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardarparametros, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, 130, 50));

        txtobservacion.setColumns(20);
        txtobservacion.setRows(5);
        jScrollPane2.setViewportView(txtobservacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 520, 100));

        lblobservacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblobservacion.setText("OBERVACION:");
        jPanel1.add(lblobservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncambiarmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiarmedicoActionPerformed
        // TODO add your handling code here:
        // 1. Obtener el ID del médico seleccionado en el JComboBox
        int index = cbxmedicos.getSelectedIndex();
        if (index >= 0) {
            DoctorDTO medico = listaDoctores.get(index);

            try {
                // 2. Obtener la lista filtrada
                List<PruebaResumenDTO> lista = pruebaService.obtenerResumenPorMedico(medico.getId());

                // 3. Cargar el JList
                DefaultListModel<String> model = new DefaultListModel<>();
                for (PruebaResumenDTO p : lista) {
                    model.addElement(p.toString());
                }
                jList1.setModel(model);

            } catch (NegocioException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_btncambiarmedicoActionPerformed

    private void btnguardarparametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarparametrosActionPerformed
        // TODO add your handling code here:
        String folioActual = lblEscribirfolio.getText();
        String observacionTexto = txtobservacion.getText();

        if (folioActual == null || folioActual.equals("escribir folio") || folioActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Debe buscar un folio primero.");
            return;
        }

        try {
            // 2. Obtener el ID de la prueba desde la BD
            PruebaEntidad prueba = pruebaDAO.buscarPorFolio(folioActual);
            Long idPrueba = prueba.getId_prueba();

            DefaultTableModel model = (DefaultTableModel) jtableparametros.getModel();

            // 3. Recorrer la tabla para guardar cada fila
            for (int i = 0; i < model.getRowCount(); i++) {
                String valor = (String) model.getValueAt(i, 1);

                // Omitir filas vacías si es necesario
                if (valor == null || valor.trim().isEmpty()) {
                    continue;
                }

                ParametroDTO p = this.listaParametrosCargados.get(i);

                // 4. Llamar al servicio pasando los 4 parámetros
                resultadoService.registrarResultado(p.getId(), idPrueba, valor, observacionTexto);
            }

            JOptionPane.showMessageDialog(this, "Resultados y observación guardados exitosamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnguardarparametrosActionPerformed

    private void btncapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapturarActionPerformed

        String seleccion = jList1.getSelectedValue();
        if (seleccion == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una prueba de la lista.");
            return;
        }

        try {
            // 2. Extraer el folio
            String folio = seleccion.split(" \\| ")[0].replace("Folio: ", "");

            // 3. Obtener el detalle del paciente
            PruebaDetalleDTO detalle = pruebaService.obtenerDetallePrueba(folio);

            // 4. Llenar los Labels
            lblnombredelpaciente.setText(detalle.getNombrePaciente());
            lblescribirid.setText(detalle.getIdPaciente());
            lblescribirsexo.setText(detalle.getSexo());
            lblnombremedico.setText(detalle.getNombreMedico());
            lblescribirfechadetoma.setText(detalle.getFechaToma());
            lblEscribirfolio.setText(folio);

            // 5. Cargar los análisis en la lista de clase y en el JComboBox
            // Usamos la lista de clase listaAnalisisActuales para que btncambiar pueda usarla después
            listaAnalisisActuales = pruebaService.obtenerAnalisisPorFolio(folio);

            cbxanalisis.removeAllItems();
            for (AnalisisDTO analisis : listaAnalisisActuales) {
                cbxanalisis.addItem(analisis.getNombre());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al capturar datos: " + ex.getMessage());
        }


    }//GEN-LAST:event_btncapturarActionPerformed

    private void btncambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiarActionPerformed
        int index = cbxanalisis.getSelectedIndex();

        // 2. Validar que la selección sea válida
        if (index < 0 || index >= listaAnalisisActuales.size()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un análisis válido.");
            return;
        }

        AnalisisDTO seleccionado = listaAnalisisActuales.get(index);

        try {
            // 4. Obtener parámetros usando el ID del DTO
            this.listaParametrosCargados = parametroService.obtenerPorAnalisis(seleccionado.getId());

            // 5. Cargar los datos en la tabla
            DefaultTableModel model = (DefaultTableModel) jtableparametros.getModel();
            model.setRowCount(0);

            for (ParametroDTO p : this.listaParametrosCargados) {
                model.addRow(new Object[]{
                    p.getNombre(),
                    "", 
                    p.getUnidad(),
                    p.getRangoFormateado()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los parámetros: " + e.getMessage());
            Logger.getLogger(Ingreso_resultados.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btncambiarActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        // TODO add your handling code here:
        javax.swing.JFrame ventanaContenedora = new javax.swing.JFrame("Reportes");

        Reportes panelReportes = new Reportes();

        ventanaContenedora.getContentPane().add(panelReportes);

        ventanaContenedora.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ventanaContenedora.pack(); 
        ventanaContenedora.setLocationRelativeTo(null);

        ventanaContenedora.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnresultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresultadosActionPerformed

    private void btnsolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolicitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsolicitudesActionPerformed

    private void btncatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ingreso_resultados().setVisible(true);
                } catch (PersistenciaException ex) {
                    Logger.getLogger(Ingreso_resultados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPMENUDEPRINCIPAL;
    private javax.swing.JPanel JPPENDIENTES;
    private javax.swing.JButton btncambiar;
    private javax.swing.JButton btncambiarmedico;
    private javax.swing.JButton btncapturar;
    private javax.swing.JButton btncatalogo;
    private javax.swing.JButton btnguardarparametros;
    private javax.swing.JButton btnreportes;
    private javax.swing.JButton btnresultados;
    private javax.swing.JButton btnsolicitudes;
    private javax.swing.JComboBox<String> cbxanalisis;
    private javax.swing.JComboBox<String> cbxmedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jlistadependientes;
    private javax.swing.JTable jtableparametros;
    private javax.swing.JLabel lblEscribirfolio;
    private javax.swing.JLabel lblescribirfechadetoma;
    private javax.swing.JLabel lblescribirid;
    private javax.swing.JLabel lblescribirsexo;
    private javax.swing.JLabel lblnombredelpaciente;
    private javax.swing.JLabel lblnombremedico;
    private javax.swing.JLabel lblobservacion;
    private javax.swing.JLabel lblpendientes;
    private javax.swing.JTextArea txtobservacion;
    // End of variables declaration//GEN-END:variables
}
