/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import dtos.PruebaDetalleDTO;
import dtos.ResultadoDTO;
import exception.PersistenciaException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import servicios.PruebaService;
import servicios.ReporteService;

/**
 *
 * @author golea
 */
public class Reportes extends javax.swing.JPanel {

    private servicios.PruebaService pruebaService = new servicios.PruebaService();

    /**
     * Creates new form Reportes
     */
    public Reportes() {

        initComponents();
        cargarLista();
    }

    private void cargarLista() {
        // 1. Instanciamos el servicio (asegúrate de tener el método en PruebaService)
        PruebaService service = new PruebaService();

        // 2. Creamos el modelo para el JList
        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();

        // 3. Obtenemos la lista filtrada
        java.util.List<dtos.ClientePruebaCompletaDTO> lista = service.obtenerClientesCompletos();

        for (dtos.ClientePruebaCompletaDTO c : lista) {
            modelo.addElement(c.getFolio() + " - " + c.getNombreCliente());
        }

        // 4. Actualizamos el JList
        jList1.setModel(modelo);
    }

    private String generarHTMLReporte(dtos.ReportePacienteDTO datos) {
        StringBuilder sb = new StringBuilder();

        // Configuración de estilos CSS para un reporte clínico profesional
        sb.append("<html><head><style>");
        sb.append("body { font-family: Arial, sans-serif; margin: 30px; color: #333; }");
        sb.append("h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; text-align: center; }");
        sb.append("h2 { color: #2c3e50; text-align: center; margin-top: 10px; }");
        sb.append(".header-box { background-color: #f8f9fa; padding: 15px; border: 1px solid #dee2e6; border-radius: 5px; margin-bottom: 25px; }");
        sb.append(".header-box p { margin: 5px 0; font-size: 14px; }");
        sb.append("table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }");
        sb.append("th { background-color: #3498db; color: white; padding: 10px; text-align: left; border: 1px solid #2980b9; }");
        sb.append("td { border: 1px solid #ddd; padding: 8px; }");
        sb.append("tr:nth-child(even) { background-color: #f2f2f2; }");
        sb.append("</style></head><body>");

        // Título del documento
        sb.append("<h1>Reporte de Resultados Médicos</h1>");

        // Datos del paciente
        sb.append("<div class='header-box'>");
        sb.append("<p><strong>Paciente:</strong> ").append(datos.getNombrePaciente()).append("</p>");
        sb.append("<p><strong>Folio:</strong> ").append(datos.getFolio()).append(" &#160;&#160; <strong>Sexo:</strong> ").append(datos.getSexo()).append("</p>");
        sb.append("<p><strong>Doctor:</strong> ").append(datos.getNombreMedico()).append("</p>");
        sb.append("<p><strong>Fecha:</strong> ").append(datos.getFechaToma()).append("</p>");
        sb.append("</div>");

        // Nombre del análisis
        sb.append("<h2>Análisis: ").append(datos.getNombreAnalisis()).append("</h2>");

        // Tabla de resultados
        sb.append("<table>");
        sb.append("<tr><th>Parámetro</th><th>Valor</th><th>Unidad</th><th>Valores Ref.</th><th>Observación</th></tr>");

        // Ciclo para llenar los resultados
        for (dtos.ResultadoReporteDTO res : datos.getResultados()) {
            sb.append("<tr>");
            sb.append("<td>").append(res.getNombreParametro()).append("</td>");
            sb.append("<td>").append(res.getValor()).append("</td>");
            sb.append("<td>").append(res.getUnidades()).append("</td>");
            sb.append("<td>").append(res.getValorMin()).append(" - ").append(res.getValorMax()).append("</td>");
            sb.append("<td>").append(res.getObservacion()).append("</td>");
            sb.append("</tr>");
        }

        sb.append("</table></body></html>");

        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelfondo = new javax.swing.JPanel();
        JPMENUDEPRINCIPAL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btncatalogo = new javax.swing.JButton();
        btnsolicitudes = new javax.swing.JButton();
        btnresultados = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPPENDIENTES = new javax.swing.JPanel();
        lblpendientes = new javax.swing.JLabel();
        jlistadependientes = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnbuscar = new javax.swing.JButton();
        txtbuscador = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnprevisualizar = new javax.swing.JButton();

        jpanelfondo.setBackground(new java.awt.Color(102, 255, 204));
        jpanelfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPMENUDEPRINCIPAL.setBackground(new java.awt.Color(31, 41, 55));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salud Total");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion de Laboratorio");

        btncatalogo.setText("Catalogo");
        btncatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalogoActionPerformed(evt);
            }
        });

        btnsolicitudes.setText("Solicitudes");
        btnsolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolicitudesActionPerformed(evt);
            }
        });

        btnresultados.setText("Resultados");
        btnresultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresultadosActionPerformed(evt);
            }
        });

        btnreportes.setText("Reportes");
        btnreportes.setToolTipText("");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPMENUDEPRINCIPALLayout = new javax.swing.GroupLayout(JPMENUDEPRINCIPAL);
        JPMENUDEPRINCIPAL.setLayout(JPMENUDEPRINCIPALLayout);
        JPMENUDEPRINCIPALLayout.setHorizontalGroup(
            JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMENUDEPRINCIPALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnreportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(btncatalogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsolicitudes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnresultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPMENUDEPRINCIPALLayout.setVerticalGroup(
            JPMENUDEPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMENUDEPRINCIPALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(114, 114, 114)
                .addComponent(btncatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnresultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreportes)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        jpanelfondo.add(JPMENUDEPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 690));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Emision de Reportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpanelfondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 750, 50));

        lblpendientes.setText("Validados");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistadependientes.setViewportView(jList1);

        btnbuscar.setText("buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtbuscador.setText("jTextField1");
        txtbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPPENDIENTESLayout = new javax.swing.GroupLayout(JPPENDIENTES);
        JPPENDIENTES.setLayout(JPPENDIENTESLayout);
        JPPENDIENTESLayout.setHorizontalGroup(
            JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                        .addComponent(jlistadependientes)
                        .addGap(36, 36, 36))
                    .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                        .addComponent(lblpendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JPPENDIENTESLayout.setVerticalGroup(
            JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPENDIENTESLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPPENDIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpendientes)
                    .addComponent(btnbuscar)
                    .addComponent(txtbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jlistadependientes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jpanelfondo.add(JPPENDIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 330, 640));

        btnprevisualizar.setText("Previsualizar");
        btnprevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnprevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnprevisualizar)
                .addGap(17, 17, 17))
        );

        jpanelfondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncatalogoActionPerformed

    private void btnsolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolicitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsolicitudesActionPerformed

    private void btnresultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresultadosActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Instanciar la ventana de destino
            pantallas.Ingreso_resultados ventanaIngreso = new pantallas.Ingreso_resultados();

            // 2. Hacer visible la nueva ventana
            ventanaIngreso.setVisible(true);

            // 3. Cerrar la ventana que contiene al panel actual
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();

        } catch (Exception e) {
            // Aquí manejas cualquier error inesperado
            javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir la pantalla: " + e.getMessage());
        }
    }//GEN-LAST:event_btnresultadosActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        String filtro = txtbuscador.getText().toLowerCase().trim();

        // 1. Obtener todos los datos nuevamente (o usar una lista cacheada)
        PruebaService service = new PruebaService();
        List<dtos.ClientePruebaCompletaDTO> listaCompleta = service.obtenerClientesCompletos();

        // 2. Crear un nuevo modelo para el JList
        javax.swing.DefaultListModel<String> modeloFiltrado = new javax.swing.DefaultListModel<>();

        // 3. Filtrar
        for (dtos.ClientePruebaCompletaDTO c : listaCompleta) {
            // Comparamos el folio o el nombre con el texto del buscador
            if (c.getFolio().toLowerCase().contains(filtro)
                    || c.getNombreCliente().toLowerCase().contains(filtro)) {

                modeloFiltrado.addElement(c.getFolio() + " - " + c.getNombreCliente());
            }
        }

        // 4. Asignar el modelo filtrado al JList
        jList1.setModel(modeloFiltrado);

        // Validar si no se encontraron resultados
        if (modeloFiltrado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        }

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadorActionPerformed

    private void btnprevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevisualizarActionPerformed
        String seleccion = jList1.getSelectedValue();
        if (seleccion == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la lista.");
            return;
        }

        String folio = seleccion.split(" - ")[0];
        servicios.ReporteService service = new servicios.ReporteService();
        dtos.ReportePacienteDTO datos = service.generarReporte(folio);

        if (datos != null) {
            try {
                // 1. Construir el HTML
                String html = generarHTMLReporte(datos);

                // 2. Definir ruta de salida
                String nombreArchivo = "Reporte_" + folio + ".pdf";

                // 3. Convertir a PDF
                try (java.io.OutputStream os = new java.io.FileOutputStream(nombreArchivo)) {
                    com.openhtmltopdf.pdfboxout.PdfRendererBuilder builder = new com.openhtmltopdf.pdfboxout.PdfRendererBuilder();
                    builder.withHtmlContent(html, "/");
                    builder.toStream(os);
                    builder.run();
                }

                // 4. Abrir automáticamente
                java.awt.Desktop.getDesktop().open(new java.io.File(nombreArchivo));

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnprevisualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPMENUDEPRINCIPAL;
    private javax.swing.JPanel JPPENDIENTES;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncatalogo;
    private javax.swing.JButton btnprevisualizar;
    private javax.swing.JButton btnreportes;
    private javax.swing.JButton btnresultados;
    private javax.swing.JButton btnsolicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jlistadependientes;
    private javax.swing.JPanel jpanelfondo;
    private javax.swing.JLabel lblpendientes;
    private javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
